import React, { useState } from 'react';
import { 
  Banknote, 
  Search, 
  Filter, 
  Eye, 
  Check, 
  X, 
  Send,
  Download,
  AlertCircle
} from 'lucide-react';
import { Card, Button, Badge } from '../components/UI';
import { Modal } from '../components/Modal';
import toast from 'react-hot-toast';

type PayrollBatch = {
  id: string;
  month: string;
  employees: number;
  amount: number;
  status: 'Pending' | 'Approved' | 'Rejected' | 'Released';
};

const INITIAL_PAYROLLS: PayrollBatch[] = [
  { id: '1', month: 'July 2026', employees: 520, amount: 820000, status: 'Pending' },
  { id: '2', month: 'June 2026', employees: 515, amount: 810500, status: 'Released' },
  { id: '3', month: 'May 2026', employees: 510, amount: 805000, status: 'Released' },
];

export const PayrollApproval: React.FC = () => {
  const [payrolls, setPayrolls] = useState<PayrollBatch[]>(INITIAL_PAYROLLS);
  const [searchTerm, setSearchTerm] = useState('');
  const [isReviewModalOpen, setIsReviewModalOpen] = useState(false);
  const [selectedBatch, setSelectedBatch] = useState<PayrollBatch | null>(null);

  const filteredPayrolls = payrolls.filter(p => 
    p.month.toLowerCase().includes(searchTerm.toLowerCase()) || 
    p.status.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const getStatusBadge = (status: PayrollBatch['status']) => {
    switch (status) {
      case 'Pending':
        return <Badge variant="warning">Pending Review</Badge>;
      case 'Approved':
        return <Badge variant="success">Approved</Badge>;
      case 'Rejected':
        return <Badge variant="error">Rejected</Badge>;
      case 'Released':
        return <Badge variant="primary">Salary Released</Badge>;
      default:
        return <Badge variant="default">{status}</Badge>;
    }
  };

  const handleAction = (id: string, newStatus: PayrollBatch['status']) => {
    setPayrolls(prev => prev.map(p => {
      if (p.id === id) {
        return { ...p, status: newStatus };
      }
      return p;
    }));
    toast.success(`Payroll batch marked as ${newStatus}`);
    setIsReviewModalOpen(false);
  };

  const openReviewModal = (batch: PayrollBatch) => {
    setSelectedBatch(batch);
    setIsReviewModalOpen(true);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Payroll Approvals</h1>
          <p className="text-sm text-slate-500 mt-1">Review and approve monthly payroll generated by the Payroll Manager.</p>
        </div>
      </div>

      <Card className="bg-white border-slate-200">
        <div className="p-4 border-b border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="relative w-full sm:w-72">
            <Search className="w-5 h-5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input 
              type="text"
              placeholder="Search month or status..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
            />
          </div>
          <Button variant="outline" className="w-full sm:w-auto gap-2">
            <Filter className="w-4 h-4" />
            Filter
          </Button>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-slate-600">
            <thead className="bg-slate-50 text-slate-500 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 font-medium">Month</th>
                <th className="px-6 py-4 font-medium text-right">Employees</th>
                <th className="px-6 py-4 font-medium text-right">Amount</th>
                <th className="px-6 py-4 font-medium">Status</th>
                <th className="px-6 py-4 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredPayrolls.map((batch) => (
                <tr key={batch.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 font-medium text-slate-900">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-primary-50 text-primary-600 flex items-center justify-center shrink-0">
                        <Banknote className="w-5 h-5" />
                      </div>
                      {batch.month}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-right font-medium">{batch.employees}</td>
                  <td className="px-6 py-4 text-right font-bold text-slate-900">
                    ${batch.amount.toLocaleString()}
                  </td>
                  <td className="px-6 py-4">
                    {getStatusBadge(batch.status)}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex justify-end gap-2">
                      <Button 
                        variant="ghost" 
                        size="sm" 
                        onClick={() => openReviewModal(batch)}
                        title="Review Payroll"
                        className="text-slate-400 hover:text-blue-600"
                      >
                        <Eye className="w-4 h-4" />
                      </Button>
                      
                      {batch.status === 'Pending' && (
                        <>
                          <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => handleAction(batch.id, 'Approved')}
                            title="Approve"
                            className="text-slate-400 hover:text-emerald-600"
                          >
                            <Check className="w-4 h-4" />
                          </Button>
                          <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => handleAction(batch.id, 'Rejected')}
                            title="Reject"
                            className="text-slate-400 hover:text-rose-600"
                          >
                            <X className="w-4 h-4" />
                          </Button>
                        </>
                      )}

                      {batch.status === 'Approved' && (
                        <Button 
                          variant="primary" 
                          size="sm" 
                          onClick={() => handleAction(batch.id, 'Released')}
                          title="Release Salary"
                          className="gap-2"
                        >
                          <Send className="w-4 h-4" /> Release
                        </Button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
              
              {filteredPayrolls.length === 0 && (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-slate-500">
                    <Banknote className="w-12 h-12 text-slate-300 mx-auto mb-3" />
                    <p className="text-lg font-medium text-slate-900 mb-1">No payroll batches found</p>
                    <p>Try adjusting your search terms.</p>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      <Modal
        isOpen={isReviewModalOpen}
        onClose={() => setIsReviewModalOpen(false)}
        title="Review Payroll Batch"
      >
        {selectedBatch && (
          <div className="space-y-6">
            <div className="bg-slate-50 rounded-xl p-4 border border-slate-100 flex items-start gap-4">
              <div className="w-12 h-12 rounded-full bg-primary-100 text-primary-600 flex items-center justify-center shrink-0">
                <Banknote className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-slate-900">{selectedBatch.month} Payroll</h3>
                <p className="text-slate-500 text-sm">Generated by Payroll Manager</p>
              </div>
              <div className="ml-auto">
                {getStatusBadge(selectedBatch.status)}
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white border border-slate-200 rounded-xl p-4">
                <p className="text-sm font-bold text-slate-400 uppercase mb-1">Total Employees</p>
                <p className="text-2xl font-black text-slate-800">{selectedBatch.employees}</p>
              </div>
              <div className="bg-white border border-slate-200 rounded-xl p-4">
                <p className="text-sm font-bold text-slate-400 uppercase mb-1">Total Amount</p>
                <p className="text-2xl font-black text-slate-800">${selectedBatch.amount.toLocaleString()}</p>
              </div>
            </div>

            <div className="bg-blue-50 text-blue-800 p-4 rounded-xl flex items-start gap-3">
              <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
              <p className="text-sm">Please verify the total amount against the generated payroll reports before approving. Once approved, the funds can be released to the bank.</p>
            </div>

            <div className="flex gap-3 justify-end pt-4 border-t border-slate-200">
              <Button variant="outline" className="gap-2">
                <Download className="w-4 h-4" /> Download Report
              </Button>
              {selectedBatch.status === 'Pending' && (
                <>
                  <Button variant="outline" className="text-rose-600 border-rose-200 hover:bg-rose-50" onClick={() => handleAction(selectedBatch.id, 'Rejected')}>
                    Reject
                  </Button>
                  <Button variant="primary" onClick={() => handleAction(selectedBatch.id, 'Approved')}>
                    Approve
                  </Button>
                </>
              )}
              {selectedBatch.status === 'Approved' && (
                <Button variant="primary" onClick={() => handleAction(selectedBatch.id, 'Released')} className="gap-2">
                  <Send className="w-4 h-4" /> Release to Bank
                </Button>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};
